from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import SM_Street_App.urls
from SM_Street_App import views

urlpatterns = [
    path('', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('login_action', views.login_action, name="login_action"),

    # ////////////////////// Admin ///////////////////////

    path('admin_home', views.admin_home, name="admin_home"),
    path('shop_verify', views.shop_verify, name="shop_verify"),
    path('shop_verify_search', views.shop_verify_search, name="shop_verify_search"),
    path('shop_accept/<int:shop_id>', views.shop_accept, name="shop_accept"),
    path('shop_reject/<int:shop_id>', views.shop_reject, name="shop_reject"),
    path('view_category', views.view_category, name="view_category"),
    path('add_category', views.add_category, name="add_category"),
    path('add_category_action', views.add_category_action, name="add_category_action"),
    path('delete_category/<int:cat_id>', views.delete_category, name="delete_category"),
    path('view_shop_rating', views.view_shop_rating, name="view_shop_rating"),
    path('search_shop_action', views.search_shop_action, name="search_shop_action"),
    path('view_complaint_type', views.view_complaint_type, name="view_complaint_type"),
    path('view_complaint_type_action', views.view_complaint_type_action, name="view_complaint_type_action"),
    path('view_complaint_search', views.view_complaint_search, name="view_complaint_search"),
    path('complaint_reply/<int:complaint_id>', views.complaint_reply, name="complaint_reply"),
    path('complaint_reply_action', views.complaint_reply_action, name="complaint_reply_action"),
    path('shop_complaint_reply/<int:complaint_id>', views.shop_complaint_reply, name="shop_complaint_reply"),
    path('shop_complaint_reply_action', views.shop_complaint_reply_action, name="shop_complaint_reply_action"),
    path('view_shop_complaint_search', views.view_shop_complaint_search, name="view_shop_complaint_search"),
    # path('select_shop_notification', views.select_shop_notification, name="select_shop_notification"),
    path('send_notification', views.send_notification, name="send_notification"),
    path('send_notification_action', views.send_notification_action, name="send_notification_action"),
    path('approve_sellers', views.approve_sellers, name="approve_sellers"),
    path('accept_seller/<int:seller_id>', views.accept_seller, name="accept_seller"),
    path('reject_seller/<int:seller_id>', views.reject_seller, name="reject_seller"),
    path('approve_sellers_search', views.approve_sellers_search, name="approve_sellers_search"),


    # ////////////////////////////////////// RENTAL //////////////////////////////////////////

    path('rental_register', views.rental_register, name="rental_register"),
    path('rental_register_action', views.rental_register_action, name="rental_register_action"),
    path('rental_home', views.rental_home, name="rental_home"),
    path('view_booking', views.view_booking, name="view_booking"),
    path('view_booking_search', views.view_booking_search, name="view_booking_search"),
    path('manage_product', views.manage_product, name="manage_product"),
    path('manage_product_search', views.manage_product_search, name="manage_product_search"),
    path('add_rental_product', views.add_rental_product, name="add_rental_product"),
    path('add_rental_product_action', views.add_rental_product_action, name="add_rental_product_action"),
    path('update_rental_product/<int:product_id>', views.update_rental_product, name="update_rental_product"),
    path('delete_rental_product/<int:product_id>', views.delete_rental_product, name="delete_rental_product"),
    path('update_rental_product_action', views.update_rental_product_action, name="update_rental_product_action"),
    path('view_more_booking/<int:booking_id>', views.view_more_booking, name="view_more_booking"),
    path('accept_rental_request', views.accept_rental_request, name="accept_rental_request"),
    path('reject_rental_request', views.reject_rental_request, name="reject_rental_request"),

    # ////////////////////////////////////// SHOP //////////////////////////////////////////////

    path('shop_register', views.shop_register, name="shop_register"),
    path('shop_register_action', views.shop_register_action, name="shop_register_action"),
    path('shop_home', views.shop_home, name="shop_home"),
    path('manage_shop_product', views.manage_shop_product, name="manage_shop_product"),
    path('manage_shop_product_search', views.manage_shop_product_search, name="manage_shop_product_search"),
    path('add_shop_product', views.add_shop_product, name="add_shop_product"),
    path('add_shop_product_action', views.add_shop_product_action, name="add_shop_product_action"),
    path('update_shop_product/<int:product_id>', views.update_shop_product, name="update_shop_product"),
    path('update_shop_product_action', views.update_shop_product_action, name="update_shop_product_action"),
    path('delete_shop_product/<int:product_id>', views.delete_shop_product, name="delete_shop_product"),
    path('manage_offers', views.manage_offers, name="manage_offers"),
    path('manage_offers_search', views.manage_offers_search, name="manage_offers_search"),
    path('add_offers', views.add_offers, name="add_offers"),
    path('add_offer_action', views.add_offer_action, name="add_offer_action"),
    path('update_offers/<int:offer_id>', views.update_offers, name="update_offers"),
    path('update_offer_action', views.update_offer_action, name="update_offer_action"),
    path('delete_offers/<int:offer_id>', views.delete_offers, name="delete_offers"),
    path('view_notifications_shop', views.view_notifications_shop, name="view_notifications_shop"),
    path('view_rating_review', views.view_rating_review, name="view_rating_review"),
    path('view_rating_review_search', views.view_rating_review_search, name="view_rating_review_search"),
    path('manage_special_offers', views.manage_special_offers, name="manage_special_offers"),
    path('manage_special_offers_search', views.manage_special_offers_search, name="manage_special_offers_search"),
    path('add_special_offers', views.add_special_offers, name="add_special_offers"),
    path('add_special_offer_action', views.add_special_offer_action, name="add_special_offer_action"),
    path('update_special_offers/<int:offer_id>', views.update_special_offers, name="update_special_offers"),
    path('update_special_offer_action', views.update_special_offer_action, name="update_special_offer_action"),
    path('delete_special_offers/<int:offer_id>', views.delete_special_offers, name="delete_special_offers"),
    path('send_complaint_view_reply', views.send_complaint_view_reply, name="send_complaint_view_reply"),
    path('send_complaint', views.send_complaint, name="send_complaint"),
    path('send_complaint_action', views.send_complaint_action, name="send_complaint_action"),
    path('complaint_search', views.complaint_search, name="complaint_search"),
    path('update_stock', views.update_stock, name="update_stock"),
    path('add_shop_product_stock', views.add_shop_product_stock, name="add_shop_product_stock"),
    path('add_shop_product_stock_action', views.add_shop_product_stock_action, name="add_shop_product_stock_action"),
    path('update_shop_product_stock/<int:stock_id>', views.update_shop_product_stock, name="update_shop_product_stock"),
    path('update_shop_stock_action', views.update_shop_stock_action, name="update_shop_stock_action"),
    path('product_stock_search', views.product_stock_search, name="product_stock_search"),
    path('insert_user_details', views.insert_user_details, name="insert_user_details"),
    path('insert_user_details1', views.insert_user_details1, name="insert_user_details1"),
    path('manage_bill', views.manage_bill, name="manage_bill"),
    path('add_new', views.add_new, name="add_new"),
    path('add_order/<int:stock_id>', views.add_order, name="add_order"),
    path('add_order1', views.add_order1, name="add_order1"),
    path('finish', views.finish, name="finish"),
    path('view_booking_update_status', views.view_booking_update_status, name="view_booking_update_status"),
    path('booking_update/<int:booking_id>', views.booking_update, name="booking_update"),
    path('booking_accept', views.booking_accept, name="booking_accept"),
    path('booking_reject', views.booking_reject, name="booking_reject"),

    # # ////////////////////////////////////////// SELLER ///////////////////////////////////////////////////
    #
    # path('seller_register', views.seller_register, name="seller_register"),
    # path('seller_registration_action', views.seller_registration_action, name="seller_registration_action"),
    # path('seller_home', views.seller_home, name="seller_home"),
    # path('manage_sellers_product', views.manage_sellers_product, name="manage_sellers_product"),
    # path('add_sellers_product', views.add_sellers_product, name="add_sellers_product"),
    # path('add_sellers_product_action', views.add_sellers_product_action, name="add_sellers_product_action"),
    # path('update_seller_product/<int:product_id>', views.update_seller_product, name="update_seller_product"),
    # path('update_sellers_product_action', views.update_sellers_product_action, name="update_sellers_product_action"),
    # path('delete_seller_product/<int:product_id>', views.delete_seller_product, name="delete_seller_product"),
    # path('search_sellers_product', views.search_sellers_product, name="search_sellers_product"),
    # path('update_seller_status', views.update_seller_status, name="update_seller_status"),
    #
    # /////////////////////////////////////////// USER ///////////////////////////////////////////////////////

    path('login_code', views.login_code, name="login_code"),
    path('user_registration', views.user_registration, name="user_registration"),
    path('view_shop', views.view_shop, name="view_shop"),
    path('search_view_shop', views.search_view_shop, name="search_view_shop"),
    path('view_offers', views.view_offers, name="view_offers"),
    path('search_view_offers', views.search_view_offers, name="search_view_offers"),
    path('view_special_offers', views.view_special_offers, name="view_special_offers"),
    path('search_view_special_offers', views.search_view_special_offers, name="search_view_special_offers"),
    path('view_notification_user', views.view_notification_user, name="view_notification_user"),
    path('view_category_user', views.view_category_user, name="view_category_user"),
    path('view_products_user', views.view_products_user, name="view_products_user"),
    path('shop_product_rating', views.shop_product_rating, name="shop_product_rating"),
    path('shop_complaints_reply', views.shop_complaints_reply, name="shop_complaints_reply"),
    path('view_shop_name', views.view_shop_name, name="view_shop_name"),
    path('send_shop_complaint', views.send_shop_complaint, name="send_shop_complaint"),
    path('search_user_complaints_reply', views.search_user_complaints_reply, name="search_user_complaints_reply"),
    path('view_rental_products_user', views.view_rental_products_user, name="view_rental_products_user"),
    path('view_rental', views.view_rental, name="view_rental"),
    path('search_view_rental', views.search_view_rental, name="search_view_rental"),
    path('orders', views.orders, name="orders"),
    path('order_shop_products', views.order_shop_products, name="order_shop_products"),

    # //////////////////////////////////////// SELLER ////////////////////////////////////////////////////

    path('seller_registration', views.seller_registration, name="seller_registration"),
    path('view_product', views.view_product, name="view_product"),
    path('add_product', views.add_product, name="add_product"),
    path('delete_product', views.delete_product, name="delete_product"),
    path('edit_product_view', views.edit_product_view, name="edit_product_view"),
    path('edit_product', views.edit_product, name="edit_product"),
    path('update_seller_status', views.update_seller_status, name="update_seller_status"),
    path('update_location', views.update_location, name="update_location"),

]
