# Generated by Django 3.2.20 on 2023-10-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
                ('ProductDetails', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=20)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.category')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityNo', models.CharField(max_length=20)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('Amount', models.CharField(max_length=20)),
                ('RENTAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.rental')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockNo', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Details', models.CharField(max_length=20)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Status', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
                ('ProductDetails', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=20)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.category')),
                ('RENTAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
                ('QUANTITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.quantity')),
                ('RENTAL_BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.rentalbooking')),
            ],
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.user'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratings', models.CharField(max_length=20)),
                ('Reviews', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Details', models.CharField(max_length=20)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notifications', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SELLER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILLING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.billing')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
                ('QUANTITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.quantity')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.shop'),
        ),
    ]
