# Generated by Django 3.2.20 on 2023-10-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
