# Generated by Django 3.2.20 on 2023-11-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0002_auto_20231031_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbookingdetails',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.rentalproduct'),
        ),
    ]
