# Generated by Django 3.2.20 on 2023-11-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0004_auto_20231102_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Latitude',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='Longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
