# Generated by Django 3.2.20 on 2023-11-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0005_auto_20231111_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
