# Generated by Django 3.2.20 on 2023-11-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0007_alter_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='Phone',
        ),
    ]
