# Generated by Django 3.2.20 on 2023-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0008_remove_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
