# Generated by Django 3.2.20 on 2023-11-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0009_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='SHOP',
        ),
    ]
