# Generated by Django 3.2.20 on 2023-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0010_remove_notification_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='QUANTITY',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Quantity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
