# Generated by Django 3.2.20 on 2023-11-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0011_auto_20231115_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='Username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
