# Generated by Django 3.2.20 on 2023-11-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0012_auto_20231116_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='PRODUCT',
        ),
        migrations.AddField(
            model_name='booking',
            name='Amount',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.booking')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.product')),
            ],
        ),
    ]
