# Generated by Django 3.2.20 on 2023-11-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0013_auto_20231116_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='complaint',
            name='SHOP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.user'),
            preserve_default=False,
        ),
    ]
