# Generated by Django 3.2.20 on 2023-11-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0014_auto_20231116_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='StockNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
