# Generated by Django 3.2.20 on 2023-11-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0015_rentalproduct_stockno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbooking',
            name='RENTAL',
        ),
    ]
