# Generated by Django 3.2.20 on 2023-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0016_remove_rentalbooking_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='DOB',
        ),
        migrations.AddField(
            model_name='seller',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
