# Generated by Django 3.2.20 on 2023-11-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0017_auto_20231117_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='Longitude',
        ),
    ]
