# Generated by Django 3.2.20 on 2023-11-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM_Street_App', '0019_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.shop')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM_Street_App.user')),
            ],
        ),
    ]
